### ISSUE TITLE
All uploads failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/anaconda-client-feedstock#10]
It seems we are unable to upload `anaconda-client` of late. Not entirely sure what went wrong, but this is happening for all OSes and Pythons. Hoping that upgrading to the newest version of `anaconda-client` will fix this problem, but currently that is blocked due to upstream bugs on Windows.

**Comment by damianavila** [comment]
The failure is not informative after #9 according to what I saw in TravisCI, is there any way you/we can chime in the build to investigate why the anaconda upload is failing... I mean get some other more informative error than `not exit 0`?

**Comment by jakirkham** [comment]
We can copy and paste the [`upload_or_check_non_existence.py`]( https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/235b16f2b9801b14a7d6cc65ac7989aac736fbb2/recipe/upload_or_check_non_existence.py ) file in the recipe and re-render. That will use the upload script from our recipe and not the one from `conda-forge-build-setup`. At that point, we can tweak that script as needed to get more info. We could put this on a non-`master` branch at the main repo here to avoid having to mess with `master` too much.

**Comment by damianavila** [comment]
Sounds like a good idea!! Btw, see: https://github.com/Anaconda-Platform/anaconda-client/issues/398#issuecomment-295900500

**Comment by damianavila** [comment]
FYI, anaconda-client 1.6.3 containing the win fix was released, @jakirkham.

**Comment by jakirkham** [comment]
Feel free to do a PR if you have time, @damianavila. I'm swamped with other things ATM. 😅

**Comment by jakirkham** [comment]
This seems to have been resolved by upgrading to 1.6.3. However, this raises more questions than it answers. In particular, it makes me wonder if not packaging the same version of `anaconda-client` as `defaults` was somehow causing the problem. Will keep this in mind as we go forward.

**Comment by damianavila** [comment]
> Will keep this in mind as we go forward.

Thanks... 
And thanks for building it... here swamped with other things as well :wink:
