### ISSUE TITLE
nbformat dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/anaconda-client-feedstock#14]
Does anaconda-client really depend on nbformat?

**Comment by jakirkham** [comment]
Apparently, it failed an import test without it. Also please see PR ( https://github.com/Anaconda-Platform/anaconda-client/pull/429 ) where this change came about.

**Comment by jakirkham** [comment]
Basically this is needed for validating notebooks before uploading them with `anaconda-client`.
