### ISSUE TITLE
Dependencies on pillow and anaconda-project

### ISSUE THREAD

**Issue by mbargull** [conda-forge/anaconda-client-feedstock#49]
### Comment:

In https://github.com/conda-forge/anaconda-client-feedstock/pull/36
```
anaconda-project>=0.9.1
pillow>=8.2
```
from https://github.com/Anaconda-Platform/anaconda-client/blob/1.11.1/requirements-extra.txt have been added as hard dependencies.

This is generally fine since it is common for conda-forge packages to ship optional dependencies by default.

In this case though, we drag in some unneeded/unwanted baggage for all our CI runs since our infrastructure depends on this packages.
Concrete, we have
1. `pillow` itself which is a unreasonably large (over 40MB) package since https://github.com/conda-forge/pillow-feedstock/issues/117 has not been resolved.
1. `anaconda-project` ~~(transitively) drags in 22 more dependencies (currently on `linux-64` when creating a fresh environment)~~:
    1. ~~nearly all those dependencies are small,~~
    1. ~~but it also includes `pillow`, i.e., see above,~~
    1. \[EDIT\] scratch that above; that was only due to `anaconda-project` depending on `anaconda-client` itself;
        so, we may just want to remove that cyclic dependency,
    1. and it includes the unneeded/unmaintained `ruamel_yaml` which I'd like to remove generally.

(As for the last point, I've opened a PR orthogonal to this issue to switch `anaconda-project` to `ruamel.yaml` at https://github.com/Anaconda-Platform/anaconda-project/pull/399 .)

----
Could we either remove this dependencies again or create a sub package `anaconda-client-XXX` which does not include those?

**Comment by jakirkham** [comment]
@vshevchenko-anaconda would be interested to hear your thoughts here?

Also curious to know whether these dependencies could be softened upstream

**Comment by mbargull** [comment]
(N.B.: If/when we do this, we have to coordinate this with @isuruf since it affects other infrastructure things he works on.)

**Comment by jakirkham** [comment]
What are Pillow and Anaconda-Project used for?

Asking to understand how this would affect other things

**Comment by mbargull** [comment]
> What are Pillow and Anaconda-Project used for?

- `anaconda-project`: uploading Anaconda projects.
- `pillow`: converting/creating icons/thumbnails when inspecting conda packages/ipynbs or uploading ipynbs.

Those are comparatively niche uses so inclusion by default has less benefit in comparison to improved resource usage.
In case there's going to be demand for this, we can address this in future *whilst ensuring the default use cases are not as negatively impacted*.

----
For comparison, https://github.com/AnacondaRecipes/anaconda-client-feedstock/blob/9b0bfa3b9fec973b4911cf65efcb4e997d2c3db8/recipe/meta.yaml#L29 also does not include those by default.

**Comment by isuruf** [comment]
Support for both will be removed in future anaconda.org as mentioned in the last meeting.

**Comment by mbargull** [comment]
Ah, nice, thanks for mentioning that!
(Ha, I only joined the meeting after that has been discussed and didn't check the notes, whoops.)

**Comment by jakirkham** [comment]
Projects and environments are being removed

Don't recall them mentioning icons. That said, Idk whether these see much usage now

**Comment by jaimergp** [comment]
It's been two years and Pillow is still there, so I opened https://github.com/anaconda/anaconda-client/pull/924 to remove it for good. `icon` entries are still used reasonably in the ecosystem and they are part of the upload payload for some reason.
